
# Assignment: Data Structures, Functions, NumPy & Pandas


# Section A: Data Structures & Control Structures

## A1) List operations

In [1]:
# Create a list of 5 integers
nums = [10, 20, 30, 40, 50]
print("Original list:", nums)

# append
nums.append(60)
print("After append(60):", nums)

# extend
nums.extend([70, 80])
print("After extend([70, 80]):", nums)

# insert
nums.insert(2, 25)  # insert 25 at index 2
print("After insert(2, 25):", nums)

# remove (removes first occurrence of value)
nums.remove(40)
print("After remove(40):", nums)

# pop (removes by index; default removes last)
popped_value = nums.pop()
print("After pop():", nums, "| popped:", popped_value)

# index (find index of first occurrence)
idx_30 = nums.index(30)
print("Index of 30:", idx_30)

# count (count occurrences)
count_20 = nums.count(20)
print("Count of 20:", count_20)

# sort
nums.sort()
print("After sort():", nums)

# reverse
nums.reverse()
print("After reverse():", nums)

# clear
nums.clear()
print("After clear():", nums)


Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop(): [10, 20, 25, 30, 50, 60, 70] | popped: 80
Index of 30: 3
Count of 20: 1
After sort(): [10, 20, 25, 30, 50, 60, 70]
After reverse(): [70, 60, 50, 30, 25, 20, 10]
After clear(): []


## A2) Tuple immutability

In [2]:
# Create a tuple with 3 student names
students = ("Asha", "Rahul", "Meera")
print("Original tuple:", students)

# Try changing the second name (index 1)
try:
    students[1] = "Ravi"
except TypeError as e:
    print("Error:", e)

print("\nExplanation:")
print("- Tuples are immutable in Python, meaning their items cannot be changed after creation.")
print("- So assigning a new value to students[1] causes a TypeError.")


Original tuple: ('Asha', 'Rahul', 'Meera')
Error: 'tuple' object does not support item assignment

Explanation:
- Tuples are immutable in Python, meaning their items cannot be changed after creation.
- So assigning a new value to students[1] causes a TypeError.


## A3) Set with duplicates

In [3]:
# Create a set with duplicate integers
num_set = {1, 2, 2, 3, 3, 3, 4}
print("Set output:", num_set)

print("\nExplanation:")
print("- Sets store only unique values.")
print("- Duplicate values are automatically removed.")


Set output: {1, 2, 3, 4}

Explanation:
- Sets store only unique values.
- Duplicate values are automatically removed.


## A4) Dictionary update and add new key

In [4]:
# Create dictionary
person = {"name": "Neha", "age": 25, "city": "Bangalore"}
print("Original dictionary:", person)

# Update age
person["age"] = 26

# Add new key 'email'
person["email"] = "neha@example.com"

print("Updated dictionary:", person)


Original dictionary: {'name': 'Neha', 'age': 25, 'city': 'Bangalore'}
Updated dictionary: {'name': 'Neha', 'age': 26, 'city': 'Bangalore', 'email': 'neha@example.com'}


## A5) Voting eligibility (age ≥ 18)

In [5]:
# Take age as a variable
age = 17  # change this value to test

if age >= 18:
    print("Eligible to vote.")
else:
    print("Not eligible to vote.")


Not eligible to vote.


## A6) Grade based on marks

In [6]:
marks = 82  # change this value to test

if marks >= 90:
    grade = "A"
elif 75 <= marks <= 89:
    grade = "B"
elif 50 <= marks <= 74:
    grade = "C"
else:
    grade = "Fail"

print("Marks:", marks, "-> Grade:", grade)


Marks: 82 -> Grade: B


## A7) Check positive and even / zero / negative

In [7]:
num = -4  # change this value to test

if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")


The number is negative.


# Section B: NumPy

## B1) Scalar, 1D array, 2D array

In [8]:
import numpy as np

# Scalar using np.array(5)
scalar = np.array(5)
print("Scalar:", scalar, "| shape:", scalar.shape)

# 1D array with values 1 to 5
arr_1d = np.array([1, 2, 3, 4, 5])
print("\n1D array:", arr_1d, "| shape:", arr_1d.shape)

# 2D array (2x3) with values 10 to 60 in steps of 10
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("\n2D array:\n", arr_2d, "| shape:", arr_2d.shape)


Scalar: 5 | shape: ()

1D array: [1 2 3 4 5] | shape: (5,)

2D array:
 [[10 20 30]
 [40 50 60]] | shape: (2, 3)


## B2) 4x4 random integer array (0 to 100)

In [9]:
# Set seed so results are reproducible
np.random.seed(42)

rand_arr = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Array:\n", rand_arr)


4x4 Random Array:
 [[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]


## B3) Convert 3x3 NumPy array to DataFrame with columns A, B, C

In [10]:
import pandas as pd

arr_3x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

df_from_np = pd.DataFrame(arr_3x3, columns=["A", "B", "C"])
df_from_np


A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

# Section C: Exploring Pandas

## C1) Create a DataFrame manually (10 rows)

In [11]:
import pandas as pd
import numpy as np

# Create a small DataFrame manually with 10 rows
data = {
    "Name":   ["Asha", "Rahul", "Meera", "Vikram", "Neha", "Sara", "Karan", "Diya", "Rohit", "Meera"],
    "Age":    [23, 28, 25, 30, 26, 29, 24, 27, 31, 25],
    "City":   ["Bangalore", "Chennai", "Delhi", "Mumbai", "Bangalore", "Delhi", "Chennai", "Mumbai", "Delhi", "Delhi"],
    "Salary": [50000, 65000, np.nan, 72000, 58000, 70000, 61000, np.nan, 80000, np.nan]
}

df = pd.DataFrame(data)
df


Name  Age       City   Salary
0    Asha   23  Bangalore  50000.0
1   Rahul   28    Chennai  65000.0
2   Meera   25      Delhi      NaN
3  Vikram   30     Mumbai  72000.0
4    Neha   26  Bangalore  58000.0
5    Sara   29      Delhi  70000.0
6   Karan   24    Chennai  61000.0
7    Diya   27     Mumbai      NaN
8   Rohit   31      Delhi  80000.0
9   Meera   25      Delhi      NaN

## C2) Use .info() and .describe()

In [12]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  7 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [13]:
df.describe(include="all")


Name       Age   City        Salary
count      10  10.00000     10      7.000000
unique      9       NaN      4           NaN
top     Meera       NaN  Delhi           NaN
freq        2       NaN      4           NaN
mean      NaN  26.80000    NaN  65142.857143
std       NaN   2.65832    NaN   9906.707684
min       NaN  23.00000    NaN  50000.000000
25%       NaN  25.00000    NaN  59500.000000
50%       NaN  26.50000    NaN  65000.000000
75%       NaN  28.75000    NaN  71000.000000
max       NaN  31.00000    NaN  80000.000000

## C3) Select 'Name' and 'City' columns

In [14]:
df[["Name", "City"]].head()


Name       City
0    Asha  Bangalore
1   Rahul    Chennai
2   Meera      Delhi
3  Vikram     Mumbai
4    Neha  Bangalore

## C4) Drop 'City' column

In [15]:
df_dropped = df.drop(columns=["City"])
df_dropped.head()


Name  Age   Salary
0    Asha   23  50000.0
1   Rahul   28  65000.0
2   Meera   25      NaN
3  Vikram   30  72000.0
4    Neha   26  58000.0

## C5) Fill missing values in 'Salary' with mean

In [16]:
salary_mean = df["Salary"].mean()
print("Mean salary (ignoring NaN):", salary_mean)

df_filled = df.copy()
df_filled["Salary"] = df_filled["Salary"].fillna(salary_mean)
df_filled


Mean salary (ignoring NaN): 65142.857142857145


Name  Age       City        Salary
0    Asha   23  Bangalore  50000.000000
1   Rahul   28    Chennai  65000.000000
2   Meera   25      Delhi  65142.857143
3  Vikram   30     Mumbai  72000.000000
4    Neha   26  Bangalore  58000.000000
5    Sara   29      Delhi  70000.000000
6   Karan   24    Chennai  61000.000000
7    Diya   27     Mumbai  65142.857143
8   Rohit   31      Delhi  80000.000000
9   Meera   25      Delhi  65142.857143

## C6) Remove duplicate rows

In [17]:
print("Number of duplicate rows:", df_filled.duplicated().sum())

df_no_duplicates = df_filled.drop_duplicates()
print("Shape before:", df_filled.shape, "Shape after:", df_no_duplicates.shape)

df_no_duplicates


Number of duplicate rows: 1
Shape before: (10, 4) Shape after: (9, 4)


Name  Age       City        Salary
0    Asha   23  Bangalore  50000.000000
1   Rahul   28    Chennai  65000.000000
2   Meera   25      Delhi  65142.857143
3  Vikram   30     Mumbai  72000.000000
4    Neha   26  Bangalore  58000.000000
5    Sara   29      Delhi  70000.000000
6   Karan   24    Chennai  61000.000000
7    Diya   27     Mumbai  65142.857143
8   Rohit   31      Delhi  80000.000000